services:
  caddy:
    build:
        context: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DOMAIN=${CADDY_DOMAIN}
      - EMAIL=${CADDY_EMAIL}
      - LOG_FILE=/data/access.log
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  Caddyfile: